### ISSUE TITLE
bytebase/rollout-action@v2 Unrecognized value name 'github'

### ISSUE THREAD

**Issue by jjfaoisdf** [bytebase/rollout-action#15]
I'm using Bytebase v3.5.0 and bytebase/rollout-action@v2 .
When trying to rollout changes via my github action, which is based on this example: https://github.com/bytebase/example-gitops-github-flow/blob/main/.github/workflows/release.yml , I get the following error, which I was not getting 2 days ago:

```
Error: bytebase/rollout-action/v2/action.yml (Line: 22, Col: 7): Unrecognized named-value: 'github'. Located at position 1 within expression: github.event.head_commit.message
Error: Failed to load bytebase/rollout-action/v2/action.yml
```

**Comment by jjfaoisdf** [comment]
Also tried with rollout-action@v2.0.2 the latest and got the same error.

**Comment by jjfaoisdf** [comment]
I haven't found the error yet, and comparing against the example release.yml from my initial comment, the fields look identical.
For help troubleshooting, this is what the yml looks like (with identifying environment variable values cleared out):
```
name: Build and push release image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build app and upload
        run: |
          echo "Building..."
          echo "Build done!"
          echo "Uploading..."
          echo "Upload done!"
  deploy-to-dev:
    needs: build
    runs-on: ubuntu-latest # use self-hosted machines if your Bytebase runs in internal networks.
    environment: dev
    env:
      BYTEBASE_URL:
      BYTEBASE_SERVICE_ACCOUNT: 
      BYTEBASE_PROJECT: 
      BYTEBASE_TARGETS:
      FILE_PATTERN: "migrations/*.sql"
    outputs:
      bytebase-plan: ${{ steps.create-plan.outputs.plan }}
      deployment-required: ${{ steps.create-plan.outputs.deployment-required }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: bytebase/login-action@v1
        with:
          bytebase-url: ${{ env.BYTEBASE_URL }}
          service-key: ${{ env.BYTEBASE_SERVICE_ACCOUNT }}
          service-secret: ${{secrets.BYTEBASE_PASSWORD}} # Please use secrets for sensitive data in production.
      - name: Create release
        id: create-release
        uses: bytebase/create-release-action@v1
        with:
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          file-pattern: ${{ env.FILE_PATTERN }}
          # fail the action if release checks report any error.
          check-release: "FAIL_ON_ERROR"
          project: ${{ env.BYTEBASE_PROJECT }}
          targets: ${{ env.BYTEBASE_TARGETS }}
          validate-only: false
      - name: Create plan
        id: create-plan
        uses: bytebase/create-plan-from-release-action@v1
        with:
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          project: ${{ env.BYTEBASE_PROJECT }}
          release: ${{ steps.create-release.outputs.release }}
          targets: ${{ env.BYTEBASE_TARGETS }}
          check-plan: "SKIP"
      - name: Rollout
        id: rollout
        uses: bytebase/rollout-action@v2.0.2
        if: ${{ steps.create-plan.outputs.deployment-required == 'true' }}
        with:
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          plan: ${{ steps.create-plan.outputs.plan }}
          target-stage: environments/dev # the dev environment.
      - name: Deploy app
        run: |
          echo "Deploying app to dev environment..."
          echo "Deploy app to dev environment done!"
```
